// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBFirstApproach.Models;

public partial class TblProduct
{
    public int ProductId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }

    public int CategoryId { get; set; }

    public virtual TblCategory Category { get; set; }
}